/*
 * This file is generated by jOOQ.
*/
package com.ewellhealth.jooq.autogen;


import com.ewellhealth.jooq.autogen.tables.Username;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jooq</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERNAME_PRIMARY = Indexes0.USERNAME_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERNAME_PRIMARY = Internal.createIndex("PRIMARY", Username.USERNAME, new OrderField[] { Username.USERNAME.ID }, true);
    }
}
