/*
 * This file is generated by jOOQ.
*/
package com.ewellhealth.jooq.autogen;


import com.ewellhealth.jooq.autogen.tables.Username;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.username</code>.
     */
    public static final Username USERNAME = com.ewellhealth.jooq.autogen.tables.Username.USERNAME;
}
